# Site
name: 'Nefomemes'
description: 'Hi there! I do coding and stuff.'
logo: 'https://avatars0.githubusercontent.com/u/66000635?s=460&u=50cb7de6be18e934cea4e5c3b298893497c0047f&v=4'
favicon: 'https://avatars0.githubusercontent.com/u/66000635?s=460&u=50cb7de6be18e934cea4e5c3b298893497c0047f&v=4'
baseurl: '/blog/'
disqus: 'nefomemes'
email: 'nefothingy@hotmail.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    nefo:
      name:           Nefomemes
      site:           /
      avatar:         https://avatars0.githubusercontent.com/u/66000635?s=460&u=50cb7de6be18e934cea4e5c3b298893497c0047f&v=4   
      bio:            "Hi, I'm Nefomemes, just a young programmer learning how to code."
      email:          nefothingy@hotmail.com
      twitter:        https://twitter.com/ForTombstone 
      

         
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
