# Site
name: 'Nefomemes'
description: 'Hi there! I do coding and stuff.'
logo: "assets/images/nefo.png"
favicon: "assets/images/nefo.png"
baseurl: '/blog'
disqus: nefomemes
email: nefothingy@hotmail.com
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    nefo:
      name:           Nefomemes
      site: "https://nefomemes.github.io"
      avatar: "assets/images/nefo.png"   
      bio:            "Hi, I'm Nefomemes, just a young programmer learning how to code."
      email:          nefothingy@hotmail.com
      twitter:        https://twitter.com/ForTombstone 
      

         
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [.replit, README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
